# Generated by Django 5.2.6 on 2025-10-20 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='language_logos/')),
                ('description', models.TextField()),
                ('year_created', models.IntegerField()),
                ('main_application_area', models.CharField(choices=[('web', 'Web Development'), ('mobile', 'Mobile Development'), ('desktop', 'Desktop Applications'), ('data_science', 'Data Science & AI'), ('systems', 'Systems Programming'), ('game', 'Game Development'), ('embedded', 'Embedded Systems')], max_length=50)),
                ('is_popular', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
