# Generated by Django 5.2.7 on 2025-10-20 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('languages_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='language',
            name='is_popular',
        ),
        migrations.AddField(
            model_name='language',
            name='last_viewed',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='language',
            name='view_count',
            field=models.IntegerField(default=0),
        ),
    ]
